sudo: required # required root permission to run

services:
  - docker # download and run docker on travis container

before_install:
  - docker build -t quanghuy9289/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true quanghuy9289/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-412739572468"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
