sudo: required # required root permission to run

services:
  - docker # download and run docker on travis container

before_install:
  - docker build -t quanghuy9289/docker-react -f Dockerfile.dev .

scripts:
  - docker run quanghuy9289/docker-react npm run test -- --coverage
